name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate snake animation
        uses: Platane/snk@master
        id: snake-svg
        with:
          github_user_name: Prashant-Kumar-Codes
          svg_out_path: dist/github-contribution-grid-snake.svg
      
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          fqdn: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
